# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginUI(object):
    def setupUi(self, LoginUI):
        LoginUI.setObjectName("LoginUI")
        LoginUI.resize(799, 525)
        self.centralwidget = QtWidgets.QWidget(LoginUI)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 40, 351, 461))
        self.frame.setStyleSheet("#frame{\n"
"background-color:qlineargradient(spread:pad, x1:0.523, y1:0, x2:0.545, y2:0.977, stop:0 rgba(112, 93, 232, 255), stop:1 rgba(255, 0, 0, 255));\n"
"border-radius:20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 130, 251, 91))
        self.label.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 30pt \"宋体\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(90, 240, 301, 41))
        self.label_2.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 20pt \"仿宋\";")
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(370, 50, 361, 441))
        self.frame_2.setStyleSheet("#frame_2{\n"
"    background-color:rgb(255, 255, 255);\n"
"    border-top-right-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(340, 0, 21, 23))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 20, 351, 391))
        self.frame_3.setMinimumSize(QtCore.QSize(270, 330))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.StackedWidget = QtWidgets.QStackedWidget(self.frame_6)
        self.StackedWidget.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"    border-bottom:1px solid black;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"")
        self.StackedWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.StackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.StackedWidget.setObjectName("StackedWidget")
        self.Login_page = QtWidgets.QWidget()
        self.Login_page.setObjectName("Login_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Login_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.log_un = QtWidgets.QLineEdit(self.Login_page)
        self.log_un.setMinimumSize(QtCore.QSize(0, 30))
        self.log_un.setObjectName("log_un")
        self.verticalLayout_3.addWidget(self.log_un)
        self.log_pw = QtWidgets.QLineEdit(self.Login_page)
        self.log_pw.setMinimumSize(QtCore.QSize(0, 30))
        self.log_pw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.log_pw.setObjectName("log_pw")
        self.verticalLayout_3.addWidget(self.log_pw)
        self.log_ens = QtWidgets.QPushButton(self.Login_page)
        self.log_ens.setMinimumSize(QtCore.QSize(0, 35))
        self.log_ens.setObjectName("log_ens")
        self.verticalLayout_3.addWidget(self.log_ens)
        self.StackedWidget.addWidget(self.Login_page)
        self.Register_page = QtWidgets.QWidget()
        self.Register_page.setObjectName("Register_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Register_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.reg_un = QtWidgets.QLineEdit(self.Register_page)
        self.reg_un.setMinimumSize(QtCore.QSize(0, 25))
        self.reg_un.setText("")
        self.reg_un.setObjectName("reg_un")
        self.verticalLayout_4.addWidget(self.reg_un)
        self.reg_pw = QtWidgets.QLineEdit(self.Register_page)
        self.reg_pw.setMinimumSize(QtCore.QSize(0, 25))
        self.reg_pw.setObjectName("reg_pw")
        self.verticalLayout_4.addWidget(self.reg_pw)
        self.reg_pw_2 = QtWidgets.QLineEdit(self.Register_page)
        self.reg_pw_2.setMinimumSize(QtCore.QSize(0, 25))
        self.reg_pw_2.setObjectName("reg_pw_2")
        self.verticalLayout_4.addWidget(self.reg_pw_2)
        self.reg_ens = QtWidgets.QPushButton(self.Register_page)
        self.reg_ens.setMinimumSize(QtCore.QSize(0, 30))
        self.reg_ens.setObjectName("reg_ens")
        self.verticalLayout_4.addWidget(self.reg_ens)
        self.StackedWidget.addWidget(self.Register_page)
        self.horizontalLayout_3.addWidget(self.StackedWidget)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_login = QtWidgets.QPushButton(self.frame_7)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/loginin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.frame_login.setIcon(icon1)
        self.frame_login.setIconSize(QtCore.QSize(16, 16))
        self.frame_login.setObjectName("frame_login")
        self.horizontalLayout_2.addWidget(self.frame_login)
        self.frame_register = QtWidgets.QPushButton(self.frame_7)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/reg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.frame_register.setIcon(icon2)
        self.frame_register.setObjectName("frame_register")
        self.horizontalLayout_2.addWidget(self.frame_register)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_2.raise_()
        self.frame.raise_()
        LoginUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginUI)
        self.StackedWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(LoginUI.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginUI)

    def retranslateUi(self, LoginUI):
        _translate = QtCore.QCoreApplication.translate
        LoginUI.setWindowTitle(_translate("LoginUI", "MainWindow"))
        self.label.setText(_translate("LoginUI", "学生管理系统"))
        self.label_2.setText(_translate("LoginUI", "欢迎您的使用"))
        self.log_un.setPlaceholderText(_translate("LoginUI", "用户名:"))
        self.log_pw.setPlaceholderText(_translate("LoginUI", "密码:"))
        self.log_ens.setText(_translate("LoginUI", "确认"))
        self.reg_un.setPlaceholderText(_translate("LoginUI", "用户名："))
        self.reg_pw.setPlaceholderText(_translate("LoginUI", "密码："))
        self.reg_pw_2.setPlaceholderText(_translate("LoginUI", "确认密码:"))
        self.reg_ens.setText(_translate("LoginUI", "注册"))
        self.frame_login.setText(_translate("LoginUI", "Login"))
        self.frame_register.setText(_translate("LoginUI", "Register"))
import icon_rc
